// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BruteForce","status":false,"description":"それいけぼくらのブルートフォース用プラグイン","parameters":{}},
{"name":"FontLoad","status":false,"description":"フォントロードプラグイン","parameters":{"フォント名1":"basic","フォントURL1":"mplus.ttf","フォント名2":"","フォントURL2":"","フォント名3":"","フォントURL3":"","ロード完了まで待機":"false"}}
];
